services:
  app:
    build:
      context: app
      target: development
    env_file:
      - .env
    ports:
      - '3000:3000'
    volumes:
      - ./app:/app
  inngest:
    image: inngest/inngest:v0.27.0
    command: 'inngest dev -u http://app:3000/api/inngest'
    ports:
      - '8288:8288'
